services:
  - type: web
    name: symptom-ml-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: HF_HUB_ENABLE_HF_TRANSFER
        value: "1"
